In [1]:

import tensorflow as tf
tf.config.run_functions_eagerly(True)
a=tf.constant('hello world')
print(a.numpy())

b'hello world'


In [3]:
import tensorflow as tf
a=tf.constant('hello world')
print(a)

b=tf.Session()
print(b.run(a))
b.close()

tf.Tensor(b'hello world', shape=(), dtype=string)


AttributeError: module 'tensorflow' has no attribute 'Session'

In [4]:
#Sclar constants
a=tf.constant(42)
b=tf.constant(3.14)
c=tf.constant("Hello Tensorflow")
print(a)
print(a.numpy())
print(b)
print(b.numpy())
print(c)
print(c.numpy())

tf.Tensor(42, shape=(), dtype=int32)
42
tf.Tensor(3.14, shape=(), dtype=float32)
3.14
tf.Tensor(b'Hello Tensorflow', shape=(), dtype=string)
b'Hello Tensorflow'


In [5]:
#Vector constants
a=tf.constant([1,2,3])
b=tf.constant([1.0,2.0,3.0])
print(a)
print(a.numpy())
print(b)
print(b.numpy())

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
[1 2 3]
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
[1. 2. 3.]


In [6]:
#Matrix constants
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[1.0,2.0],[3.0,4.0]])
print(a)
print(a.numpy())
print(b)
print(b.numpy())

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
[[1 2]
 [3 4]]
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
[[1. 2.]
 [3. 4.]]


In [9]:
#Higher dimension constants
a=tf.constant([[[1,2,0],[3,4,0]],[[5,6,0],[7,8,0]]])
print(a)
print(a.numpy())


tf.Tensor(
[[[1 2 0]
  [3 4 0]]

 [[5 6 0]
  [7 8 0]]], shape=(2, 2, 3), dtype=int32)
[[[1 2 0]
  [3 4 0]]

 [[5 6 0]
  [7 8 0]]]


In [10]:

#Boolean constants
a=tf.constant(True)
print(a)

tf.Tensor(True, shape=(), dtype=bool)


In [11]:
#Special constants
a=tf.zeros(shape=(2,2))
b=tf.ones(shape=(3,3))
print(a)
print(a.numpy())
print(b)
print(b.numpy())

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
[[0. 0.]
 [0. 0.]]
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
import tensorflow as tf
tf.config.run_functions_eagerly(True)
a=tf.constant(5.0)
b=tf.constant(3.0)
c=tf.multiply(a,b)
result=a*b
d=a@b
print(result)
print(result.numpy())
print(d)
print(d.numpy())

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} In[0] and In[1] ndims must be == 2: 0 [Op:MatMul] name: 

In [24]:
import tensorflow as tf
a=tf.constant(1.25)
print(a)
print(a.numpy())
b=tf.cast(a,dtype=tf.int32)
print(b)
print(b.numpy())

tf.Tensor(1.25, shape=(), dtype=float32)
1.25
tf.Tensor(1, shape=(), dtype=int32)
1


In [26]:
import tensorflow as tf
x=tf.constant([[1.,2.,3.],[4.,5.,6.]])
print(x)
print(x.numpy())

e=tf.transpose(x)
print(e.numpy())

r=tf.reduce_sum(x)
print(r.numpy())

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 4.]
 [2. 5.]
 [3. 6.]]
21.0


In [28]:
x=tf.constant([[1.,2.,3.],[4.,5.,6.]])
j=x @ tf.transpose(x)
print(j.numpy())
f=tf.concat([x,x,x],axis=0)
print(f.numpy())

[[14. 32.]
 [32. 77.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]
 [4. 5. 6.]]


In [29]:
x=tf.constant([[1.0,2.0,3.0]])
logits=tf.constant([1.0,2.0])
softmax_probs=tf.nn.softmax(logits,axis=0)
print(softmax_probs)

tf.Tensor([0.26894143 0.7310586 ], shape=(2,), dtype=float32)
